name_maximum_length : 50
email_maximum_length : 50
description_maximum_length : 250
phone_minimum_length : 8
phone_maximum_length : 14
bank_account_minimum_length : 8
bank_account_maximum_length : 14
password_minimum_length : 6
remember_me : "1"
